package hooks

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/dhruvsaxena1998/cleo/internal/state"
)

var opencodeEvents = []string{
	"session.created", "tool.execute.before", "tool.execute.after",
	"permission.asked", "session.idle", "session.deleted", "session.error",
}

// OpenCodeEvents returns the lifecycle event names cleo subscribes to in opencode.
func OpenCodeEvents() []string { return append([]string(nil), opencodeEvents...) }

// openCodePluginsDir is the directory where cleo writes its opencode plugin.
// Overridden in tests to avoid touching the real home directory.
var openCodePluginsDir = ""

func openCodePlugDir() string {
	if openCodePluginsDir != "" {
		return openCodePluginsDir
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".config", "opencode", "plugins")
}

// openCodePluginTemplate is the canonical content of
// ~/.config/opencode/plugins/cleo.ts. Stored as a constant so cleo doctor
// can diff on-disk content without reading an external file.
const openCodePluginTemplate = `// Generated by ` + "`cleo init`" + ` — do not edit manually. Re-run to update.
export default async function({ $, directory }) {
  const hook = async (event, extra = {}) => {
    const payload = JSON.stringify({ cwd: directory, ...extra });
    await $` + "`" + `cleo hook opencode ${event} --payload ${payload}` + "`" + `;
  };

  return {
    hooks: {
      "session.created":     async ({ sessionID }) => hook("session.created",     { session_id: sessionID }),
      "tool.execute.before": async ({ sessionID, tool }) => hook("tool.execute.before", { session_id: sessionID, tool_name: tool }),
      "tool.execute.after":  async ({ sessionID, tool }) => hook("tool.execute.after",  { session_id: sessionID, tool_name: tool }),
      "permission.asked":    async ({ sessionID }) => hook("permission.asked",    { session_id: sessionID }),
      "session.idle":        async ({ sessionID }) => hook("session.idle",        { session_id: sessionID }),
      "session.deleted":     async ({ sessionID }) => hook("session.deleted",     { session_id: sessionID }),
      "session.error":       async ({ sessionID }) => hook("session.error",       { session_id: sessionID }),
    },
  };
}
`

// ExpectedOpenCodeEntry returns the expected content of
// ~/.config/opencode/plugins/cleo.ts. Used by cleo doctor to diff the on-disk file.
func ExpectedOpenCodeEntry() string { return openCodePluginTemplate }

type OpenCodeProtocol struct{}

func (OpenCodeProtocol) Name() string          { return "opencode" }
func (OpenCodeProtocol) Events() []string      { return OpenCodeEvents() }
func (OpenCodeProtocol) UsesCwdFallback() bool { return true }

func (OpenCodeProtocol) Install(cleoBin string, force bool) error {
	dir := openCodePlugDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	dest := filepath.Join(dir, "cleo.ts")
	existing, err := os.ReadFile(dest)
	if err == nil {
		if string(existing) == openCodePluginTemplate {
			return nil // already up-to-date; idempotent
		}
		if !force {
			return fmt.Errorf("conflict: %s already exists with different content (re-run with --force to overwrite)", dest)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(dest, []byte(openCodePluginTemplate), 0o644)
}

func (OpenCodeProtocol) Cleanup() error {
	dest := filepath.Join(openCodePlugDir(), "cleo.ts")
	content, err := os.ReadFile(dest)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	if string(content) != openCodePluginTemplate {
		fmt.Fprintf(os.Stderr, "warning: %s has been modified; skipping removal\n", dest)
		return nil
	}
	return os.Remove(dest)
}

func (OpenCodeProtocol) Normalize(event string, payload []byte) (NormalizedEvent, bool) {
	var p struct {
		ToolName string `json:"tool_name"`
	}
	_ = json.Unmarshal(payload, &p)

	switch event {
	case "session.created":
		return NormalizedEvent{StateEvent: state.EvSessionStart, SoundEvent: "session_start"}, true
	case "tool.execute.before":
		return NormalizedEvent{StateEvent: state.EvPreToolUse, ToolName: p.ToolName}, true
	case "tool.execute.after":
		return NormalizedEvent{StateEvent: state.EvPostToolUse, ToolName: p.ToolName}, true
	case "permission.asked":
		return NormalizedEvent{StateEvent: state.EvNotification, SoundEvent: "needs_input", SuppressWhenIdle: false}, true
	case "session.idle":
		return NormalizedEvent{StateEvent: state.EvStop, SoundEvent: "session_idle"}, true
	case "session.deleted":
		return NormalizedEvent{StateEvent: state.EvSessionEnd, SoundEvent: "session_completed"}, true
	case "session.error":
		return NormalizedEvent{StateEvent: state.EvError, SoundEvent: "session_error"}, true
	}
	return NormalizedEvent{}, false
}
