package hooks

import (
	"encoding/json"
	"path/filepath"

	"github.com/dhruvsaxena1998/cleo/internal/state"
)

var opencodeEvents = []string{
	"session.created", "tool.execute.before", "tool.execute.after",
	"permission.asked", "session.idle", "session.deleted", "session.error",
}

// OpenCodeEvents returns the lifecycle event names cleo subscribes to in opencode.
func OpenCodeEvents() []string { return append([]string(nil), opencodeEvents...) }

func openCodePlugDir() string {
	return filepath.Join(homeDir(), ".config", "opencode", "plugins")
}

// openCodePluginTemplate is the canonical content of
// ~/.config/opencode/plugins/cleo.ts. Stored as a constant so cleo doctor
// can diff on-disk content without reading an external file.
const openCodePluginTemplate = `// Generated by ` + "`cleo hooks init`" + ` — do not edit manually. Re-run to update.
export default {
  id: "cleo",
  server: async ({ $, directory }) => {
    const hook = async (event, extra = {}) => {
      const payload = JSON.stringify({ cwd: directory, ...extra });
      await $` + "`" + `cleo hooks invoke opencode ${event} --payload ${payload}` + "`" + `.nothrow();
    };

    return {
      event: async ({ event }) => {
        if (event.type === "session.created")
          await hook("session.created", { session_id: event.properties.info.id });
        else if (event.type === "session.idle")
          await hook("session.idle", { session_id: event.properties.sessionID });
        else if (event.type === "session.deleted")
          await hook("session.deleted", { session_id: event.properties.info.id });
        else if (event.type === "session.error")
          await hook("session.error", { session_id: event.properties.sessionID });
      },
      "tool.execute.before": async (input) => {
        await hook("tool.execute.before", { session_id: input.sessionID, tool_name: input.tool });
      },
      "tool.execute.after": async (input) => {
        await hook("tool.execute.after", { session_id: input.sessionID, tool_name: input.tool });
      },
      "permission.ask": async (input) => {
        await hook("permission.asked", { session_id: input.sessionID });
      },
    };
  },
};
`

// ExpectedOpenCodeEntry returns the expected content of
// ~/.config/opencode/plugins/cleo.ts. Used by cleo doctor to diff the on-disk file.
func ExpectedOpenCodeEntry() string { return openCodePluginTemplate }

type OpenCodeProtocol struct{}

func (OpenCodeProtocol) Name() string          { return "opencode" }
func (OpenCodeProtocol) DisplayName() string   { return "OpenCode" }
func (OpenCodeProtocol) Events() []string      { return OpenCodeEvents() }
func (OpenCodeProtocol) UsesCwdFallback() bool { return true }

func (OpenCodeProtocol) Locations() []Location {
	return []Location{{Label: "plugin", Path: filepath.Join(openCodePlugDir(), "cleo.ts")}}
}

func (OpenCodeProtocol) Install(cleoBin string, force bool) (InstallReport, error) {
	return InstallReport{}, installFileTemplate(openCodePlugDir(), "cleo.ts", openCodePluginTemplate, force)
}

func (OpenCodeProtocol) Diagnose() []Check {
	return []Check{diagnoseFileTemplate("OpenCode plugin", filepath.Join(openCodePlugDir(), "cleo.ts"), openCodePluginTemplate)}
}

func (OpenCodeProtocol) Cleanup() (CleanupOutcome, error) {
	return cleanupFileTemplate(openCodePlugDir(), "cleo.ts", openCodePluginTemplate)
}

func (OpenCodeProtocol) Normalize(event string, payload []byte) (NormalizedEvent, bool) {
	var p struct {
		ToolName string `json:"tool_name"`
	}
	_ = json.Unmarshal(payload, &p)

	switch event {
	case "session.created":
		return NormalizedEvent{StateEvent: state.EvSessionStart, SoundEvent: "session_start"}, true
	case "tool.execute.before":
		if p.ToolName == "question" {
			return NormalizedEvent{StateEvent: state.EvNotification, SoundEvent: "needs_input", ToolName: p.ToolName}, true
		}
		return NormalizedEvent{StateEvent: state.EvPreToolUse, ToolName: p.ToolName}, true
	case "tool.execute.after":
		return NormalizedEvent{StateEvent: state.EvPostToolUse, ToolName: p.ToolName}, true
	case "permission.asked":
		return NormalizedEvent{StateEvent: state.EvNotification, SoundEvent: "needs_input", SuppressWhenIdle: false}, true
	case "session.idle":
		return NormalizedEvent{StateEvent: state.EvStop, SoundEvent: "session_idle"}, true
	case "session.deleted":
		return NormalizedEvent{StateEvent: state.EvSessionEnd, SoundEvent: "session_completed"}, true
	case "session.error":
		return NormalizedEvent{StateEvent: state.EvError, SoundEvent: "session_error"}, true
	}
	return NormalizedEvent{}, false
}
