package hooks

import (
	"encoding/json"
	"path/filepath"

	"github.com/dhruvsaxena1998/cleo/internal/state"
)

var piEvents = []string{
	"session_start", "input", "tool_call", "tool_result", "agent_end", "session_shutdown",
}

// PiEvents returns the lifecycle event names cleo subscribes to in Pi.
func PiEvents() []string { return append([]string(nil), piEvents...) }

func piExtDir() string {
	return filepath.Join(homeDir(), ".pi", "agent", "extensions")
}

// piExtensionTemplate is the canonical content of ~/.pi/agent/extensions/cleo.ts.
// Stored as a constant so cleo doctor can diff on-disk content without reading an external file.
const piExtensionTemplate = `// Generated by ` + "`cleo hooks init`" + ` — do not edit manually. Re-run to update.
export default function(pi) {
  const hook = (event, ctx, extra = {}) => {
    const payload = JSON.stringify({ cwd: ctx.cwd, ...extra });
    pi.exec("cleo", ["hooks", "invoke", "pi", event, "--payload", payload], {});
  };

  pi.on("session_start",    (_, ctx) => hook("session_start",    ctx));
  pi.on("input",            (_, ctx) => hook("input",            ctx));
  pi.on("tool_call",        (e, ctx) => hook("tool_call",        ctx, { tool_name: e.toolName }));
  pi.on("tool_result",      (e, ctx) => hook("tool_result",      ctx, { tool_name: e.toolName }));
  pi.on("agent_end",        (_, ctx) => hook("agent_end",        ctx));
  pi.on("session_shutdown", (_, ctx) => hook("session_shutdown", ctx));
}
`

// ExpectedPiEntry returns the expected content of ~/.pi/agent/extensions/cleo.ts.
// Used by cleo doctor to diff the on-disk file.
func ExpectedPiEntry() string { return piExtensionTemplate }

type PiProtocol struct{}

func (PiProtocol) Name() string          { return "pi" }
func (PiProtocol) DisplayName() string   { return "Pi" }
func (PiProtocol) Events() []string      { return PiEvents() }
func (PiProtocol) UsesCwdFallback() bool { return true }

func (PiProtocol) Locations() []Location {
	return []Location{{Label: "extension", Path: filepath.Join(piExtDir(), "cleo.ts")}}
}

func (PiProtocol) Install(cleoBin string, force bool) (InstallReport, error) {
	return InstallReport{}, installFileTemplate(piExtDir(), "cleo.ts", piExtensionTemplate, force)
}

func (PiProtocol) Diagnose() []Check {
	return []Check{diagnoseFileTemplate("Pi extension", filepath.Join(piExtDir(), "cleo.ts"), piExtensionTemplate)}
}

func (PiProtocol) Cleanup() (CleanupOutcome, error) {
	return cleanupFileTemplate(piExtDir(), "cleo.ts", piExtensionTemplate)
}

func (PiProtocol) Normalize(event string, payload []byte) (NormalizedEvent, bool) {
	var p struct {
		ToolName string `json:"tool_name"`
	}
	_ = json.Unmarshal(payload, &p)

	switch event {
	case "session_start":
		return NormalizedEvent{StateEvent: state.EvSessionStart, SoundEvent: "session_start"}, true
	case "input":
		return NormalizedEvent{StateEvent: state.EvUserResume}, true
	case "tool_call":
		return NormalizedEvent{StateEvent: state.EvPreToolUse, ToolName: p.ToolName}, true
	case "tool_result":
		return NormalizedEvent{StateEvent: state.EvPostToolUse, ToolName: p.ToolName}, true
	case "agent_end":
		// Pi fires agent_end after every turn (not just when genuinely idle),
		// so suppress the sound to avoid false "done" notifications mid-task.
		return NormalizedEvent{StateEvent: state.EvStop}, true
	case "session_shutdown":
		return NormalizedEvent{StateEvent: state.EvSessionEnd, SoundEvent: "session_completed"}, true
	}
	return NormalizedEvent{}, false
}
