package hooks

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/dhruvsaxena1998/cleo/internal/state"
)

var piEvents = []string{
	"session_start", "input", "tool_call", "tool_result", "agent_end", "session_shutdown",
}

// PiEvents returns the lifecycle event names cleo subscribes to in Pi.
func PiEvents() []string { return append([]string(nil), piEvents...) }

// piExtensionsDir is the directory where cleo writes its Pi extension.
// Overridden in tests to avoid touching the real home directory.
var piExtensionsDir = ""

func piExtDir() string {
	if piExtensionsDir != "" {
		return piExtensionsDir
	}
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".pi", "agent", "extensions")
}

// piExtensionTemplate is the canonical content of ~/.pi/agent/extensions/cleo.ts.
// Stored as a constant so cleo doctor can diff on-disk content without reading an external file.
const piExtensionTemplate = `// Generated by ` + "`cleo init`" + ` — do not edit manually. Re-run to update.
export default function(pi) {
  const hook = (event, ctx, extra = {}) => {
    const payload = JSON.stringify({ cwd: ctx.cwd, ...extra });
    pi.exec("cleo", ["hook", "pi", event, "--payload", payload], {});
  };

  pi.on("session_start",    (_, ctx) => hook("session_start",    ctx));
  pi.on("input",            (_, ctx) => hook("input",            ctx));
  pi.on("tool_call",        (e, ctx) => hook("tool_call",        ctx, { tool_name: e.toolName }));
  pi.on("tool_result",      (e, ctx) => hook("tool_result",      ctx, { tool_name: e.toolName }));
  pi.on("agent_end",        (_, ctx) => hook("agent_end",        ctx));
  pi.on("session_shutdown", (_, ctx) => hook("session_shutdown", ctx));
}
`

// ExpectedPiEntry returns the expected content of ~/.pi/agent/extensions/cleo.ts.
// Used by cleo doctor to diff the on-disk file.
func ExpectedPiEntry() string { return piExtensionTemplate }

type PiProtocol struct{}

func (PiProtocol) Name() string          { return "pi" }
func (PiProtocol) Events() []string      { return PiEvents() }
func (PiProtocol) UsesCwdFallback() bool { return true }

func (PiProtocol) Install(cleoBin string, force bool) error {
	dir := piExtDir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	dest := filepath.Join(dir, "cleo.ts")
	existing, err := os.ReadFile(dest)
	if err == nil {
		if string(existing) == piExtensionTemplate {
			return nil // already up-to-date; idempotent
		}
		if !force {
			return fmt.Errorf("conflict: %s already exists with different content (re-run with --force to overwrite)", dest)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return os.WriteFile(dest, []byte(piExtensionTemplate), 0o644)
}

func (PiProtocol) Cleanup() (CleanupOutcome, error) {
	dest := filepath.Join(piExtDir(), "cleo.ts")
	content, err := os.ReadFile(dest)
	if errors.Is(err, os.ErrNotExist) {
		return CleanupOutcome{Status: CleanupStatusMissing, Path: dest}, nil
	}
	if err != nil {
		return CleanupOutcome{Path: dest}, err
	}
	if string(content) != piExtensionTemplate {
		return CleanupOutcome{Status: CleanupStatusSkippedModified, Path: dest}, nil
	}
	if err := os.Remove(dest); err != nil {
		return CleanupOutcome{Path: dest}, err
	}
	return CleanupOutcome{Status: CleanupStatusRemoved, Path: dest}, nil
}

func (PiProtocol) Normalize(event string, payload []byte) (NormalizedEvent, bool) {
	var p struct {
		ToolName string `json:"tool_name"`
	}
	_ = json.Unmarshal(payload, &p)

	switch event {
	case "session_start":
		return NormalizedEvent{StateEvent: state.EvSessionStart, SoundEvent: "session_start"}, true
	case "input":
		return NormalizedEvent{StateEvent: state.EvUserResume}, true
	case "tool_call":
		return NormalizedEvent{StateEvent: state.EvPreToolUse, ToolName: p.ToolName}, true
	case "tool_result":
		return NormalizedEvent{StateEvent: state.EvPostToolUse, ToolName: p.ToolName}, true
	case "agent_end":
		return NormalizedEvent{StateEvent: state.EvStop, SoundEvent: "session_idle"}, true
	case "session_shutdown":
		return NormalizedEvent{StateEvent: state.EvSessionEnd, SoundEvent: "session_completed"}, true
	}
	return NormalizedEvent{}, false
}
